services:
  app:
    build:
      target: production
    environment:
      - NODE_ENV=production

  client:
    build:
      context: ./app/client
      target: build

  nginx:
    build:
      target: production
    ports:
      - "8443:443"

  database:
    build:
      target: production
