services:
  app:
    build:
      target: development
    volumes:
      - ./app:/var/www/html
      - vendor_volume:/var/www/html/vendor

  client:
    build:
      context: ./app/client
      target: development
    ports:
      - "5173:5173"
    volumes:
      - ./app/client:/app
      - /app/node_modules

  nginx:
    build:
      target: development
      args:
        ENV: dev
    ports:
      - "8080:80"
    volumes:
      - ./app/public:/var/www/html/public:ro

  database:
    build:
      target: base

volumes:
  vendor_volume:
