services:
  app:
    build:
      target: production
    environment:
      - NODE_ENV=production

  nginx:
    build:
      target: production
      args:
        ENV: prod
    ports:
      - "8443:443"

  database:
    build:
      target: production
