networks:
  camagru_network:
    driver: bridge

services:
  app:
    container_name: camagru_app
    build:
      context: ./app
      dockerfile: Dockerfile
    networks:
      - camagru_network
    expose:
      - "9000"
    env_file:
      - .env
    depends_on:
      - database
    volumes:
      - media_volume:/var/www/storage/media

  nginx:
    container_name: camagru_nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    networks:
      - camagru_network
    env_file:
      - .env
    depends_on:
      - app
    volumes:
      - media_volume:/var/www/html/public/media:ro

  database:
    container_name: camagru_database
    build:
      context: ./database
      dockerfile: Dockerfile
    networks:
      - camagru_network
    expose:
      - "3306"
    env_file:
      - .env
    volumes:
      - database_volume:/var/lib/mysql

volumes:
  database_volume:
    name: database_volume
  media_volume:
    name: media_volume