services:
  app:
    build:
      target: development
    volumes:
      - ./app:/var/www/html

  nginx:
    build:
      target: development
      args:
        ENV: dev
    ports:
      - "8080:80"
    volumes:
      - ./app/public:/var/www/html/public:ro

  database:
    build:
      target: base
