services:
  app:
    build:
      target: development
    volumes:
      - ./app:/var/www/html
      - vendor_volume:/var/www/html/vendor

  nginx:
    build:
      target: development
      args:
        ENV: dev
    ports:
      - "8080:80"
    volumes:
      - ./app/public:/var/www/html/public:ro

  database:
    build:
      target: base

volumes:
  vendor_volume:
