services:
  app:
    build:
      target: production
    environment:
      - NODE_ENV=production

  cron:
    container_name: camagru_cron
    build:
      context: ./app
      dockerfile: ./cron/Dockerfile
    networks:
      - camagru_network
    env_file:
      - .env
    depends_on:
      - database

  client:
    build:
      context: ./app/client
      target: build
    entrypoint: ["sh", "-c", "cp -r /public/assets/. /output/"]
    volumes:
      - ./app/public/assets:/output

  nginx:
    build:
      target: production
    ports:
      - "8443:443"
    volumes:
      - ./app/public:/var/www/html/public:ro

  database:
    build:
      target: production
