server {
    listen 80;
    server_name localhost;

    location / {
        proxy_pass http://camagru_app:9000;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
    }

    location /assets/ {
        alias /usr/src/app/public/assets/;
    }

    client_max_body_size 10M;
}
