server {
    listen 80;
    server_name localhost;

    root /var/www/html/public;
    index index.php index.html;

    include       mime.types;
    default_type  application/octet-stream;
    sendfile      on;

    location /assets/ {
        try_files $uri $uri/ =404;
    }

    location /media/ {
        try_files $uri $uri/ =404;
        access_log off;
        expires max;
    }

    location ~ \.(php)$ {
        try_files $uri =404;
        fastcgi_pass camagru_app:9000;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
    }

    # Deny access to hidden files
    location ~ /\. {
        deny all;
    }

    client_max_body_size 10M;
}
