worker_processes auto;

events {
    worker_connections 1024;
}

http {
    access_log /var/log/nginx/access.log;
    error_log /var/log/nginx/error.log warn;

    add_header X-Content-Type-Options nosniff;
    add_header X-Frame-Options SAMEORIGIN;
    add_header X-XSS-Protection "1; mode=block";

    server {
        listen 80;
        server_name localhost;

        return 301 https://$host:8443$request_uri;
    }

    server {
        listen 443 ssl;
        server_name localhost;

        root /var/www/html/public;
        index index.html;

        ssl_certificate     /etc/nginx/ssl/camagru.crt;
        ssl_certificate_key /etc/nginx/ssl/camagru.key;
        ssl_protocols TLSv1.2 TLSv1.3;

        location = / {
            return 302 /feed;
        }

        location / {
            proxy_pass http://camagru_app:9000;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection 'upgrade';
            proxy_set_header Host $host;
            proxy_cache_bypass $http_upgrade;
        }

        location /assets/ {
            alias /usr/src/app/public/assets/;
        }

        client_max_body_size 10M;
    }
}
